// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Randomizer.Dal;

#nullable disable

namespace Randomizer.Dal.Migrations.Postgresql.Migrations
{
    [DbContext(typeof(RandomizerContext))]
    [Migration("20241109175222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Randomizer.Dal.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PlayerId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PlayerName", "UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Randomizer.Dal.PlayerPlaylist", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemotePlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemotePlaylistType")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PlayerId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Randomizer.Dal.PlaylistTrack", b =>
                {
                    b.Property<Guid>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<string>("RemoteTrackId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TrackId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("Randomizer.Dal.TrackWeight", b =>
                {
                    b.Property<Guid>("WeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<float>("WeightValue")
                        .HasColumnType("real");

                    b.HasKey("WeightId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.ToTable("TrackWeights");
                });

            modelBuilder.Entity("Randomizer.Dal.PlayerPlaylist", b =>
                {
                    b.HasOne("Randomizer.Dal.Player", "Player")
                        .WithMany("Playlists")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Randomizer.Dal.PlaylistTrack", b =>
                {
                    b.HasOne("Randomizer.Dal.PlayerPlaylist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Randomizer.Dal.TrackWeight", b =>
                {
                    b.HasOne("Randomizer.Dal.PlaylistTrack", "Track")
                        .WithOne("TrackWeight")
                        .HasForeignKey("Randomizer.Dal.TrackWeight", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Randomizer.Dal.Player", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Randomizer.Dal.PlayerPlaylist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Randomizer.Dal.PlaylistTrack", b =>
                {
                    b.Navigation("TrackWeight");
                });
#pragma warning restore 612, 618
        }
    }
}
