"""
Django settings for YoutubeMixer_project project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from configurations import Configuration


class Base(Configuration):
	# Build paths inside the project like this: BASE_DIR / 'subdir'.
	BASE_DIR = Path(__file__).resolve().parent.parent

	# SECURITY WARNING: keep the secret key used in production secret!
	SECRET_KEY = 'django-insecure-%&6-!8tu493_nab$7jy2ofol&aj00gm$-_4=!p*70^&1kf1a9i'

	DEBUG = False

	INSTALLED_APPS = [
		'django.contrib.admin',
		'django.contrib.auth',
		'django.contrib.contenttypes',
		'django.contrib.sessions',
		'django.contrib.messages',
		'rest_framework',
		"api",
		'corsheaders',
	]

	MIDDLEWARE = [
		'django.middleware.security.SecurityMiddleware',
		'django.contrib.sessions.middleware.SessionMiddleware',
		'corsheaders.middleware.CorsMiddleware',
		'django.middleware.common.CommonMiddleware',
		'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',
	]

	ROOT_URLCONF = 'YoutubeMixer_project.urls'

	TEMPLATES = [
		{
			'BACKEND': 'django.template.backends.django.DjangoTemplates',
			'DIRS': [str(BASE_DIR.joinpath("templates"))],
			'APP_DIRS': True,
			'OPTIONS': {
				'context_processors': [
					'django.template.context_processors.debug',
					'django.template.context_processors.request',
					'django.contrib.auth.context_processors.auth',
					'django.contrib.messages.context_processors.messages',
				],
			},
		},
	]

	WSGI_APPLICATION = 'YoutubeMixer_project.wsgi.application'


	# Database
	# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			'NAME': BASE_DIR / 'db.sqlite3',
		}
	}


	# Password validation
	# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

	AUTH_PASSWORD_VALIDATORS = [
		{
			'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
		},
		{
			'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
		},
		{
			'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
		},
		{
			'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
		},
	]

	ALLOWED_HOSTS = ['localhost', '0.0.0.0']

	# Internationalization
	# https://docs.djangoproject.com/en/4.0/topics/i18n/

	LANGUAGE_CODE = 'en-us'

	TIME_ZONE = 'UTC'

	USE_I18N = True

	USE_TZ = True

	DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

	SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"





class Dev(Base):
	DEBUG = True
	CORS_ALLOW_ALL_ORIGINS = True

class Prod(Base):
	DEBUG=False
