apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: youtube-randomizer-main-service
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '5'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ${SA_NAME}
      containers:
      - image: ${IMAGE}
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_CLIENT_ID
          value: ${GOOGLE_CLIENT_ID}
        - name: GOOGLE_CLIENT_SECRET
          value: ${GOOGLE_CLIENT_SECRET}
        - name: SPOTIFY_CLIENT_ID
          value: ${SPOTIFY_CLIENT_ID}
        - name: SPOTIFY_CLIENT_SECRET
          value: ${SPOTIFY_CLIENT_SECRET}
        - name: Youtube_API_Key
          value: ${Youtube_API_Key}
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 15
          failureThreshold: 2
          httpGet:
            path: /
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
