import '../styles/global/css-reset.css'
import '../styles/global/apply-theme.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import type { AppContext, AppProps } from 'next/app'
import { ThemeProvider } from 'next-themes'
import { lightTheme } from '@/styles/theme/light-theme.css'
import { darkTheme } from '@/styles/theme/dark-theme.css'
import { ApplicationHeader } from '../components/application-header'
import Head from 'next/head'
import { applicationWrapperStyle, bodyStyle, footerStyle } from '../styles/component-specific/main-layout-style.css'
import { Footer } from '../components/footer'
import { SessionProvider, getSession } from "next-auth/react"
import App from 'next/app'


export async function getInitialProps(appContext: AppContext) {
	const appProps = await App.getInitialProps(appContext)
	const session = await getSession({ req: appContext.ctx.req })

	return {
		...appProps,
		session
	}
}


export default function MyApp({
	Component,
	pageProps: { session, ...pageProps },
}: AppProps) {
	return (
		<>
			<Head>
				<title>Randomizer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<ThemeProvider attribute='class' value={{
				light: lightTheme,
				dark: darkTheme,
			}}>
				<SessionProvider session={session}>
					<div className={applicationWrapperStyle}>
						<ApplicationHeader />
						<main className={bodyStyle}>
							<Component {...pageProps} />
						</main>
						<Footer footerClassName={footerStyle} />
					</div>
				</SessionProvider>
			</ThemeProvider>
		</>
	)
}