import '../styles/global/css-reset.css'
import '../styles/global/apply-theme.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { store } from '@/store/store'
import type { AppProps } from 'next/app'
import { Provider } from 'react-redux'
import { ThemeProvider } from 'next-themes'
import { lightTheme } from '@/styles/theme/light-theme.css'
import { darkTheme } from '@/styles/theme/dark-theme.css'
import { ApplicationHeader } from '../components/application-header'
import Head from 'next/head'
import { applicationWrapperStyle, bodyStyle, footerStyle } from '../styles/component-specific/main-layout-style.css'
import { Footer } from '../components/footer'
import { FirebaseProvider } from '@/components/firebase-context'

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Youtube Randomizer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Provider store={store}>
				<FirebaseProvider>

					<ThemeProvider attribute='class' value={{
						light: lightTheme,
						dark: darkTheme,
					}}>
						<div className={applicationWrapperStyle}>
							<ApplicationHeader />
							<main className={bodyStyle}>
								<Component {...pageProps} />
							</main>
							<Footer footerClassName={footerStyle} />
						</div>
					</ThemeProvider>
				</FirebaseProvider>
			</Provider>
		</>
	)
}
