// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Randomizer.Dal;

#nullable disable

namespace Randomizer.Dal.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(RandomizerContext))]
    partial class RandomizerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Randomizer.Dal.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("PlayerId"), false);

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Id"));

                    b.HasIndex("PlayerName", "UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Randomizer.Dal.PlayerPlaylist", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemotePlaylistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemotePlaylistType")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("PlaylistId"), false);

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Id"));

                    b.HasIndex("PlayerId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Randomizer.Dal.PlaylistTrack", b =>
                {
                    b.Property<Guid>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RemoteTrackId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrackId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("TrackId"), false);

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Id"));

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistTracks");
                });

            modelBuilder.Entity("Randomizer.Dal.TrackWeight", b =>
                {
                    b.Property<Guid>("WeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("WeightValue")
                        .HasColumnType("real");

                    b.HasKey("WeightId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("WeightId"), false);

                    b.HasIndex("Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Id"));

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.ToTable("TrackWeights");
                });

            modelBuilder.Entity("Randomizer.Dal.PlayerPlaylist", b =>
                {
                    b.HasOne("Randomizer.Dal.Player", "Player")
                        .WithMany("Playlists")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Randomizer.Dal.PlaylistTrack", b =>
                {
                    b.HasOne("Randomizer.Dal.PlayerPlaylist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Randomizer.Dal.TrackWeight", b =>
                {
                    b.HasOne("Randomizer.Dal.PlaylistTrack", "Track")
                        .WithOne("TrackWeight")
                        .HasForeignKey("Randomizer.Dal.TrackWeight", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Randomizer.Dal.Player", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Randomizer.Dal.PlayerPlaylist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Randomizer.Dal.PlaylistTrack", b =>
                {
                    b.Navigation("TrackWeight");
                });
#pragma warning restore 612, 618
        }
    }
}
