import { ThemeSelector } from '@/components/theme-selector'
import { Anchor, AppShell, Burger, Divider, Flex, Group, MantineProvider, Space, Stack, Title } from '@mantine/core'
import type { AppContext, AppProps } from 'next/app'
import '@/styles/globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import '@mantine/core/styles.css';
import { NoSsr } from '@/components/no-ssr';
import Link from 'next/link';
import { useDisclosure } from '@mantine/hooks';
import { AuthButton } from '../features/header/components/auth-button';
import DefaultApp from 'next/app'
import { SupabaseClientContextProvider } from '@/features/supabase-helpers/supabase-client-context-provider';
import Head from 'next/head';
import Image from 'next/image'

App.getInitialProps = async (
	context: AppContext
) => {
	const ctx = await DefaultApp.getInitialProps(context)

	return {
		...ctx,
		PUBLIC_SUPABASE_URL: process.env.PUBLIC_SUPABASE_URL!,
		PUBLIC_SUPABASE_ANON_KEY: process.env.PUBLIC_SUPABASE_ANON_KEY!,
	}
}

export default function App({ Component, pageProps, router, PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL }: AppProps & { PUBLIC_SUPABASE_URL: string, PUBLIC_SUPABASE_ANON_KEY: string }) {
	const [opened, { toggle }] = useDisclosure();

	if (router.pathname === '/swagger-ui') {
		return <MantineProvider forceColorScheme='light'><Component {...pageProps} /></MantineProvider>
	}

	return <>
		<Head>
			<title>Randomizer</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.svg" />
		</Head>
		<MantineProvider>
			<SupabaseClientContextProvider PUBLIC_SUPABASE_ANON_KEY={PUBLIC_SUPABASE_ANON_KEY} PUBLIC_SUPABASE_URL={PUBLIC_SUPABASE_URL}>
				<AppShell style={{ minHeight: 'calc(100dvh - 30px)' }} padding="xl" header={{ height: 40 }} navbar={{
					width: 300,
					breakpoint: 'sm',
					collapsed: { mobile: !opened, desktop: !opened },
				}} footer={{ offset: true, height: 25 }}>
					<AppShell.Header>
						<Flex justify={'end'} align={'center'} gap={'lg'} style={{ height: '100%' }}>
							<Burger
								style={{ marginRight: 'auto' }}
								opened={opened}
								onClick={toggle}
								size="sm"
							/>

							<NoSsr>
								<AuthButton />
							</NoSsr>
							<NoSsr>
								<ThemeSelector />
							</NoSsr>
						</Flex>
					</AppShell.Header>
					<AppShell.Navbar p='md'>
						<Space h={'lg'} />
						<Divider my={'lg'} />

						<AppShell.Section grow>
							<Stack align='center'>
								<Anchor mx='sm' underline='never' component={Link} href={"/"}>Home</Anchor>
								<Anchor mx='sm' underline='never' component={Link} href={"/player"}>Player</Anchor>
								<Anchor mx='sm' underline='never' component={Link} href={"/playlists"}>Playlists</Anchor>
							</Stack>
						</AppShell.Section>

						<AppShell.Section>
							<Group justify='center'>
								<Link href={"/"}>
									<Image width={45} height={45} src={"/favicon.svg"} alt='site-icon' />
								</Link>
							</Group>
						</AppShell.Section>
					</AppShell.Navbar>

					<AppShell.Main>
						<Component {...pageProps} />
					</AppShell.Main>
				</AppShell>
				<Group h={'30px'} justify='center' gap={30}>
					<Anchor mx='sm' underline='never' component={Link} href="https://github.com/desmaraisp/YoutubeMixer">Source code</Anchor>
					<Anchor mx='sm' underline='never' component={Link} href={"https://philippedesmarais.netlify.app/"}>About me</Anchor>
				</Group>
			</SupabaseClientContextProvider>
		</MantineProvider>
	</>
}
