<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAotCompatible>true</IsAotCompatible>
		<AnalysisMode>Recommended</AnalysisMode>
		<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Randomizer.Dal\Randomizer.Dal.csproj" />
	</ItemGroup>

</Project>