name: Clean expired docker images

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

permissions:
  packages: write


jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'youtubemixer'
          package-type: 'container'
          min-versions-to-keep: 6
          delete-only-untagged-versions: false
