name: Deploy New Revision

on:
  push:
    branches:
    - main
    paths-ignore:
      - .github/workflows/clean-images.yml
      - "**/*.md"
      - LICENSE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Publish image
      id: publish
      env:
        FULL_TAG: docker.io/desmaraisp/youtube-randomizer:${{ github.sha }}
      run: |
        echo ${{secrets.DOCKER_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

        docker build -t $FULL_TAG -t docker.io/desmaraisp/youtube-randomizer:latest ./next-app/
        docker push docker.io/desmaraisp/youtube-randomizer --all-tags

    - name: Apply Supabase migrations
      run: |
        docker build -t migrations -f ./next-app/migrations.Dockerfile ./next-app/
        docker run -e DATABASE_URL=${{secrets.SUPABASE_DB_URI}} migrations