name: Clean old GCR images

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{vars.WorkloadIDProvider}}
        service_account: ${{vars.GCPServiceAccount}}

    - name: docker-auth
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
      with:
        args: >-
          -repo=us-central1-docker.pkg.dev/${{vars.GCPProjectID}}/main-registry/youtube-randomizer-main-release
          -keep=3