name: Run integration test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  ProjectID: temp-happy-1325234


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/327621872450/locations/global/workloadIdentityPools/gh-oidc-pool/providers/gh-oidc-pool-provider'
        service_account: 'oidc-gcp-service-account2@temp-happy-1325234.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - id: deploy-infra
      env:
        TF_VAR_ProjectID: ${{env.ProjectID}}
      run: |
        terraform -chdir=terraform/main-deployment init
        terraform -chdir=terraform/main-deployment apply -auto-approve

    - id: build-docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/${{env.ProjectID}}/nextjs-main/release:latest .
        docker push us-central1-docker.pkg.dev/${{env.ProjectID}}/nextjs-main/release
    
    - id: deploy-revision
      run: |
        gcloud run deploy nextjs-main --image us-central1-docker.pkg.dev/temp-happy-1325234/nextjs-main/release
