name: Run integration test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{vars.WorkloadIDProvider}}
        service_account: ${{vars.GCPServiceAccount}}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: deploy-infra
      env:
        TF_VAR_ProjectID: ${{vars.GCPProjectID}}
      run: |
        terraform -chdir=terraform/main-deployment init
        terraform -chdir=terraform/main-deployment apply -auto-approve

    - name: build-docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/${{vars.GCPProjectID}}/nextjs-main/release:latest .
        docker push us-central1-docker.pkg.dev/${{vars.GCPProjectID}}/nextjs-main/release
    
    - name: deploy-revision
      run: |
        gcloud run deploy nextjs-main --image us-central1-docker.pkg.dev/${{vars.GCPProjectID}}/nextjs-main/release \
          --set-env-vars="GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" \
          --set-env-vars="GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          --set-env-vars="SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" \
          --set-env-vars="SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" \
          --set-env-vars="Youtube_API_Key=${terraform output -raw Youtube_API_Key}"

